---json
{
  "title": "VP-339",
  "summary": "Integration test suite produces failure after all tests complete",
  "tags": "VP",
  "project": {
    "key": "VP",
    "title": "Video Player"
  },
  "type": "Bug",
  "priority": "Major",
  "status": "Closed",
  "resolution": "Won't Fix",
  "reporter": "Anastasia Cheetham",
  "date": "2016-01-26T15:44:53.663-0500",
  "updated": "2017-12-22T10:28:52.021-0500",
  "versions": [],
  "fixVersions": [],
  "components": [
    "core"
  ],
  "environment": null,
  "issueLinks": [],
  "attachments": [],
  "comments": [
    {
      "author": "Justin Obara",
      "date": "2017-12-22T10:28:52.019-0500",
      "body": "The video player repository has been archived.\n"
    }
  ]
}
---
<http://build.fluidproject.org/videoPlayer/tests/html/VideoPlayerIntegration-test.html>

In Firefox and Chrome, the Integration test suite produces an error after all the tests have completed, with:&#x20;

pushFailure() assertion outside test context, was     at Object.QUnit.start (<http://build.fluidproject.org/videoPlayer/tests/lib/qunit/js/qunit.js:452:10>)

In Safari, the error is a bit different: It happens during the final test, with:

Called start() while already started (QUnit.config.semaphore was 0 already)\
Expected 3 assertions, but 4 were run

        